name: run-test
on:
  push:
    branches:
      - master
      - feature/simple-test
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - 3.8
          - 3.9
          - 3.10
          - 3.11
          - 3.12
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install tox
        run: python -m pip install --prefer-binary "tox>=4.10,<5"
      - name: Setup test
        run: python -m tox -vv --notest
      - name: Run test
        run: python -m tox --skip-pkg-install
